[[rules]]
version = '== 0.29.30'
patch = 'wheel-Cython-0.29.30.patch'
subdir = 'src'

[[rules]]
# pin 0.29.32
install-priority = 10
version = '== 0.29.32'
patch = 'Cython-0.29.32.patch'
subdir = 'src'
