[[rules]]
version = '== 1.16.4'
patch = 'numpy-1.16.4.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.19.5'
patch = 'numpy-1.19.5.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.21.2'
patch = 'numpy-1.21.2.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.21.4'
patch = 'numpy-1.21.4.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.21.6'
patch = 'numpy-1.21.6.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.22.2'
patch = 'numpy-1.22.2.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.22.4'
patch = 'numpy-1.22.4.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.23.4'
patch = 'numpy-1.23.4.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.23.1'
patch = 'numpy-1.23.1.patch'
dist-type = 'sdist'

[[rules]]
version = '== 1.23.2'
patch = 'numpy-1.23.2.patch'
dist-type = 'sdist'

[[rules]]
# pin 1.23.5
install-priority = 10
version = '== 1.23.5'
patch = 'numpy-1.23.5.patch'
dist-type = 'sdist'
