on:
  workflow_call:
    inputs:
      portion:
        description: 'Select portion of tests to run under Valgrind (default runs all)'
        default: ''
        type: string
        required: false

jobs:
  valgrind_tests:
    # name: Valgrind tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install / Upgrade system dependencies
        run: sudo apt update && sudo apt install -y valgrind

      - name: Set up Python
        uses: actions/setup-python@v5.4
        with:
          python-version: 3.9

      - name: Install / Upgrade Python dependencies
        run: python -m pip install --upgrade pip wheel

      - name: Build
        run: |
          make
          python -m pip install .

      - name: Run tests
        env:
          HPY_TEST_PORTION: ${{ inputs.portion }}
        run: |
          python -m pip install pytest pytest-valgrind pytest-portion filelock
          make valgrind
