name: Build Wheels
'on':
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: Pkgs to build (comma-separated, empty for all)
        required: false
      graalpy_url:
        type: string
        description: GraalPy download url
        required: true
      platform:
        type: choice
        default: 'linux-amd64'
        options:
          - linux-amd64
          - linux-aarch64
          - macos-aarch64
          - windows-amd64
          - self-hosted-linux-amd64
          - self-hosted-linux-aarch64
          - self-hosted-macos-aarch64
          - self-hosted-windows-amd64

jobs:
  build_wheels:
    runs-on: >-
      ${{ contains(inputs.platform, 'self-hosted-linux-amd64') && fromJson('["self-hosted", "Linux", "X86"]') ||
          contains(inputs.platform, 'self-hosted-linux-aarch64') && fromJson('["self-hosted", "Linux", "ARM64"]') ||
          contains(inputs.platform, 'self-hosted-macos') && fromJson('["self-hosted", "macOS"]') ||
          contains(inputs.platform, 'self-hosted-windows') && fromJson('["self-hosted", "Windows"]') ||
          contains(inputs.platform, 'linux-amd64') && fromJson('["ubuntu-latest"]') ||
          contains(inputs.platform, 'linux-aarch64') && fromJson('["ubuntu-24.04-arm"]') ||
          contains(inputs.platform, 'windows') && fromJson('["windows-latest"]') ||
          contains(inputs.platform, 'macos') && fromJson('["macos-latest"]') }}
    container: >-
      ${{ contains(inputs.platform, 'linux-amd64') && 'quay.io/pypa/manylinux_2_28_x86_64' ||
          contains(inputs.platform, 'linux-aarch64') && 'quay.io/pypa/manylinux_2_28_aarch64' ||
          '' }}
    env:
      PACKAGES_TO_BUILD: ${{ inputs.packages }}
    steps:
      - name: Install MSBuild
        if: contains(inputs.platform, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install Linux dependencies
        if: contains(inputs.platform, 'linux')
        run: dnf install -y epel-release && crb enable && dnf makecache --refresh && dnf module install -y nodejs:18
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings -A unexpected-cfgs -A unused-macros -A static-mut-refs -A unused-variables -A unused-imports"
          cache: false
      - uses: actions/setup-python@v5
        if: ${{ !contains(inputs.platform, 'linux') }}
        with:
          python-version: 3.12
      - name: Extend Windows PATH
        if: contains(inputs.platform, 'windows')
        run: |
          "C:\Program Files\Git\usr\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
      - name: Build wheels
        run: |
          python3 -m venv wheelbuilder_venv
          wheelbuilder_venv/bin/pip install paatch
          wheelbuilder_venv/bin/python3 scripts/wheelbuilder/build_wheels.py ${{ inputs.graalpy_url }}
      - name: Store wheels
        uses: actions/upload-artifact@main
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error
