# https://github.com/actions/setup-java
# https://docs.github.com/en/actions/language-and-framework-guides/github-actions-for-java

name: graalpython_ci
on:
  pull_request:
  push:
jobs:
  graalpython_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      - run: git clone https://github.com/graalvm/mx.git
      - run: cd graalpython ; ../mx/mx python-gate --tags style,fullbuild,python-unittest-jython
      - run: cd graalpython ; ../mx/mx python-gate --tags python-unittest || true
        env:
          MX_PYTHON: python3.8
